### ISSUE TITLE
How to get the region of FA?

### ISSUE THREAD

**Issue by BubbleSai** [rshaojimmy/MultiModal-DeepFake#10]
Hi, I was wondering how to get the region of FA. In the paper's Section 3.2 (Face Attribute Manipulation), the author mentioned,  "we first predict ..... using GAN-based methods". Can I understand this as the author first applies an expression detector to the face to get the expression region (e.g., "smile mouth"), then employs StyleCLIP to modify the expression of the face, and finally replaces the original expression region with the modified expression region? 

How many face attributes does the dataset provide (e.g.,  "smile to angry")?  what is the expression detector? and is the  process of replacing as simple as copy and paste?

Thanks!

**Comment by rshaojimmy** [comment]
Hi, please check out the extension of our paper: https://arxiv.org/pdf/2309.14203.pdf and I think you could get the answers from it.

Thanks.
