### ISSUE TITLE
Details of comparison with uni-modal methods

### ISSUE THREAD

**Issue by teamwong111** [rshaojimmy/MultiModal-DeepFake#11]
Thanks for your awesome work!

I was wondering when comparing to the deepfake detection and sequence tagging methods, do you retrain the model using uni-modal data? If it is re-training, are the multi-modal-related modules such as Multi-Modal Aggregator deleted, or are all 0 data used to replace the input of another modality?

**Comment by rshaojimmy** [comment]
Hi,

Thanks for your interest in our work! 

Yes, we have retrained the model using uni-modal data without all multi-modal-related modules such as Multi-Modal Aggregator in Ours-Image and without cross-attention layers in Multi-Modal Aggregator in Ours-Text.
