### ISSUE TITLE
bert模型加载失败

### ISSUE THREAD

**Issue by shui-tian-ju-shi** [rshaojimmy/MultiModal-DeepFake#12]
貌似显示无法连接~~~求帮助
![image](https://github.com/rshaojimmy/MultiModal-DeepFake/assets/95734189/4e57a4a6-9725-40f0-a5b2-11432349824d)
![image](https://github.com/rshaojimmy/MultiModal-DeepFake/assets/95734189/a8e96f4b-3402-48f8-9c90-eedc6f2c8031)

**Comment by shui-tian-ju-shi** [comment]
我认为的是bert-base-uncased直接联网下载，还是说--text_encoder后面的默认值里需要替换成某个文件路径？

**Comment by shui-tian-ju-shi** [comment]
已解决，谢谢！

**Comment by Yang-yo** [comment]
@shui-tian-ju-shi  请问你怎么解决的
