### ISSUE TITLE
在只有图像的数据集上比如celeb-df数据集上检测，那模型中的文本模态就无法起作用了吧

### ISSUE THREAD

**Issue by shui-tian-ju-shi** [rshaojimmy/MultiModal-DeepFake#19]
我想在celeb-df数据集上测试一下hammer的性能，但我发现如果去掉文本模态，那整个模型不就仅仅相当于通过一个图像编码器然后进行分类了吗？我的理解对吗？所以hammer在单模态数据集上测试意义不大，可以这样说吗？

**Comment by maryhh** [comment]
> 我想在celeb-df数据集上测试一下hammer的性能，但我发现如果去掉文本模态，那整个模型不就仅仅相当于通过一个图像编码器然后进行分类了吗？我的理解对吗？所以hammer在单模态数据集上测试意义不大，可以这样说吗？

你测试了吗？文本可以缺省吗？
