### ISSUE TITLE
require for checkpoints

### ISSUE THREAD

**Issue by Michel-liu** [rshaojimmy/MultiModal-DeepFake#2]
Nice job! Will be the well-trained checkpoints publicly avaliable?

**Comment by rshaojimmy** [comment]
Hi, thanks for your interest in our work!

Checkpoints will be released soon. Stay tuned.

**Comment by Michel-liu** [comment]
Thanks for your reply! I have followed your original train&test bash scripts and trained with 8 V100 GPUs.  I guess there may be some hidden bugs in this code base that lead to unaligned testing results. The detailed information is listed and attached as follows for further debugging. 
testing logs:
```
{"val_AUC_cls": "92.5794", "val_ACC_cls": "85.9306", "val_EER_cls": "14.6929", "val_MAP": "84.8749", "val_OP": "78.7603", "val_OR": "80.3090", "val_OF1": "79.5271", "val_CP": "77.5541", "val_CR": "79.1858", "val_CF1": "78.3615", "val_F1_FS": "80.7870", "val_F1_FA": "83.3654", "val_F1_TS": "74.3935", "val_F1_TA": "74.6486", "val_IOU_score": "75.8431", "val_IOU_ACC_50": "83.5262", "val_IOU_ACC_75": "74.8170", "val_IOU_ACC_95": "39.2163", "val_ACC_tok": "91.7938", "val_Precision_tok": "72.8550", "val_Recall_tok": "66.3987", "val_F1_tok": "69.4772", "epoch": "best"}
```
Configs and outputs can be found in the attached file.
[log20230412_220201.zip](https://github.com/rshaojimmy/MultiModal-DeepFake/files/11219650/log20230412_220201.zip)

Thanks for your hard work again.

**Comment by liuxuannan** [comment]
Thank you for the new insight in multimodel deepfake detection! I used the pre-trained model ALBEF_4M.pth you provided to evaluate the performance, and the metrics are much lower than the results in your paper. 
test logs:{"val_AUC_cls": "43.9657", "val_ACC_cls": "34.2313", "val_EER_cls": "54.5538", "val_MAP": "21.6869", "val_OP": "20.9144", "val_OR": "78.3568", "val_OF1": "33.0164", "val_CP": "21.1200", "val_CR": "79.4151", "val_CF1": "33.3665", "val_F1_FS": "42.6327", "val_F1_FA": "34.8426", "val_F1_TS": "37.1484", "val_F1_TA": "14.5536", "val_IOU_score": "4.8990", "val_IOU_ACC_50": "0.3629", "val_IOU_ACC_75": "0.0020", "val_IOU_ACC_95": "0.0000", "val_ACC_tok": "31.8746", "val_Precision_tok": "15.6461", "val_Recall_tok": "76.3443", "val_F1_tok": "25.9699", "epoch": "best"}

**Comment by rshaojimmy** [comment]
> 

Hi, we have updated our trained checkpoint for your reference in the readme.

**Comment by rshaojimmy** [comment]
> Nice job! Will be the well-trained checkpoints publicly avaliable?

We have updated our trained checkpoint for your reference in the readme.

**Comment by rshaojimmy** [comment]
> Thank you for the new insight in multimodel deepfake detection! I used the pre-trained model ALBEF_4M.pth you provided to evaluate the performance, and the metrics are much lower than the results in your paper. test logs:{"val_AUC_cls": "43.9657", "val_ACC_cls": "34.2313", "val_EER_cls": "54.5538", "val_MAP": "21.6869", "val_OP": "20.9144", "val_OR": "78.3568", "val_OF1": "33.0164", "val_CP": "21.1200", "val_CR": "79.4151", "val_CF1": "33.3665", "val_F1_FS": "42.6327", "val_F1_FA": "34.8426", "val_F1_TS": "37.1484", "val_F1_TA": "14.5536", "val_IOU_score": "4.8990", "val_IOU_ACC_50": "0.3629", "val_IOU_ACC_75": "0.0020", "val_IOU_ACC_95": "0.0000", "val_ACC_tok": "31.8746", "val_Precision_tok": "15.6461", "val_Recall_tok": "76.3443", "val_F1_tok": "25.9699", "epoch": "best"}

Hi, you should further train the model which is initialized with pre-trained model ALBEF_4M.pth.
