### ISSUE TITLE
你好！我按照你的代码训练，训练了30多epoch，但是auc在第六遍的时候就达到了峰值，只有80，而且边界框损失bbox和giou几乎从头到尾没有发生变化。

### ISSUE THREAD

**Issue by shui-tian-ju-shi** [rshaojimmy/MultiModal-DeepFake#20]
我只是更改了一些关于多分布训练的代码，因为我是单gpu，减半了训练的批次大小。其余的没有改动。您能为我提供一些意见吗？

**Comment by huainanchen** [comment]
> 我只是更改了一些关于多分布训练的代码，因为我是单gpu，减半了训练的批次大小。其余的没有改动。您能为我提供一些意见吗？

您好！ 请问您的单卡是什么配置？

**Comment by SSOODDAA** [comment]
你好，我也遇到了相同的问题，请问您是怎么解决的呢？

**Comment by CJL0114** [comment]
你好，请问能留个联系方式一起交流一下吗？

**Comment by hysjlzn** [comment]
> 我只是更改了一些关于多分布训练的代码，因为我是单gpu，减半了训练的批次大小。其余的没有改动。您能为我提供一些意见吗？
请问一下您是怎么改的，因为我也只有一张rtx4090显卡，一直没跑通。

**Comment by shui-tian-ju-shi** [comment]
时间过去好久了，而且这篇代码我没有跟很久，所以帮不了你，不好意思了。




shui_tian_ju_shi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rshaojimmy/MultiModal-DeepFake"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月29日(星期天) 下午2:35
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [rshaojimmy/MultiModal-DeepFake] 你好！我按照你的代码训练，训练了30多epoch，但是auc在第六遍的时候就达到了峰值，只有80，而且边界框损失bbox和giou几乎从头到尾没有发生变化。 (Issue #20)





  
我只是更改了一些关于多分布训练的代码，因为我是单gpu，减半了训练的批次大小。其余的没有改动。您能为我提供一些意见吗？
 请问一下您是怎么改的，因为我也只有一张rtx4090显卡，一直没跑通。

**Comment by hysjlzn** [comment]
> 时间过去好久了，而且这篇代码我没有跟很久，所以帮不了你，不好意思了。 shui_tian_ju_shi ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rshaojimmy/MultiModal-DeepFake" ***@***.***&gt;; 发送时间:&nbsp;2024年9月29日(星期天) 下午2:35 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [rshaojimmy/MultiModal-DeepFake] 你好！我按照你的代码训练，训练了30多epoch，但是auc在第六遍的时候就达到了峰值，只有80，而且边界框损失bbox和giou几乎从头到尾没有发生变化。 (Issue #20) 我只是更改了一些关于多分布训练的代码，因为我是单gpu，减半了训练的批次大小。其余的没有改动。您能为我提供一些意见吗？ 请问一下您是怎么改的，因为我也只有一张rtx4090显卡，一直没跑通。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的，没关系，谢谢您的回复。

**Comment by garlic1234567** [comment]
> > 时间过去好久了，而且这篇代码我没有跟很久，所以帮不了你，不好意思了。 shui_tian_ju_shi _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "rshaojimmy/MultiModal-DeepFake" _**@**_._**>; 发送时间: 2024年9月29日(星期天) 下午2:35 _**@**_.**_>; _**@**_._**>;"State _**@**_.**_>; 主题: Re: [rshaojimmy/MultiModal-DeepFake] 你好！我按照你的代码训练，训练了30多epoch，但是auc在第六遍的时候就达到了峰值，只有80，而且边界框损失bbox和giou几乎从头到尾没有发生变化。 (Issue #20) 我只是更改了一些关于多分布训练的代码，因为我是单gpu，减半了训练的批次大小。其余的没有改动。您能为我提供一些意见吗？ 请问一下您是怎么改的，因为我也只有一张rtx4090显卡，一直没跑通。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 好的，没关系，谢谢您的回复。

您好，请问您解决了吗，如何修改单卡跑的代码呀。

**Comment by garlic1234567** [comment]
我也遇到了相同的情况，在训练第7个epoch时AUC达到峰值。单卡4090跑的，其他配置一致，AUC最高只有86点多。
![image](https://github.com/user-attachments/assets/efde5c10-c6d7-4e53-a8f2-98515e423abe)

**Comment by garlicyh** [comment]
你好，我也遇到了类似的情况。源码除了改成单卡4090其他未修改，训练了三十多轮AUC在第七轮达到最高87.28。
{"val_AUC_cls": "87.2804", "val_ACC_cls": "78.9607", "val_EER_cls": "20.9765", "val_MAP": "79.3490", "val_OP": "77.8541", "val_OR": "61.4960", "val_OF1": "68.7149", "val_CP": "77.0705", "val_CR": "64.3118", "val_CF1": "70.1155", "val_F1_FS": "65.7417", "val_F1_FA": "69.7367", "val_F1_TS": "69.2110", "val_F1_TA": "74.0939", "val_IOU_score": "60.2099", "val_IOU_ACC_50": "64.7648", "val_IOU_ACC_75": "49.0405", "val_IOU_ACC_95": "40.1834", "val_ACC_tok": "89.7399", "val_Precision_tok": "71.7004", "val_Recall_tok": "56.9098", "val_F1_tok": "63.4546", "epoch": "best"}

**Comment by yiersan1760** [comment]
> > 时间过去好久了，而且这篇代码我没有跟很久，所以帮不了你，不好意思了。 shui_tian_ju_shi _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "rshaojimmy/MultiModal-DeepFake" _**@**_._**>; 发送时间: 2024年9月29日(星期天) 下午2:35 _**@**_.**_>; _**@**_._**>;"State _**@**_.**_>; 主题: Re: [rshaojimmy/MultiModal-DeepFake] 你好！我按照你的代码训练，训练了30多epoch，但是auc在第六遍的时候就达到了峰值，只有80，而且边界框损失bbox和giou几乎从头到尾没有发生变化。 (Issue [#20](https://github.com/rshaojimmy/MultiModal-DeepFake/issues/20)) 我只是更改了一些关于多分布训练的代码，因为我是单gpu，减半了训练的批次大小。其余的没有改动。您能为我提供一些意见吗？ 请问一下您是怎么改的，因为我也只有一张rtx4090显卡，一直没跑通。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 好的，没关系，谢谢您的回复。

你咋解决的
