### ISSUE TITLE
CKPT download fails!

### ISSUE THREAD

**Issue by arash-aut** [rshaojimmy/MultiModal-DeepFake#26]
Hi everyone!
I tried to download [best-model-checkpoint](https://lifehkbueduhk-my.sharepoint.com/:u:/g/personal/16483782_life_hkbu_edu_hk/EfFYi4B5UXZPpYQwnaxIxDUBFd41GbHngcbW3y1Z9nfWrg?e=LfKjVK) but every time it failed!
Would you please update the link or provide another source?

**Comment by rshaojimmy** [comment]
Hi,

We have updated the link of this checkpoint. Please try it again. Thanks.

**Comment by arash-aut** [comment]
Hi, thank you so much.
