### ISSUE TITLE
DGM4 dataset is showing an error: 'This link has been removed.' 

### ISSUE THREAD

**Issue by Kirsch-Meow** [rshaojimmy/MultiModal-DeepFake#27]
Hello, the link to the DGM4 dataset is showing an error: 'This link has been removed.'T^T Is there any other way to access the dataset?

**Comment by rshaojimmy** [comment]
Hi,

Could you download our dataset via this link?
https://huggingface.co/datasets/rshaojimmy/DGM4/tree/main

Thanks.

**Comment by Kirsch-Meow** [comment]
This link works! Thank you so much!
