### ISSUE TITLE
TypeError: add_code_sample_docstrings() got an unexpected keyword argument 'tokenizer_class'

### ISSUE THREAD

**Issue by liuxuannan** [rshaojimmy/MultiModal-DeepFake#3]
Thank you for the new insight in multimodel deepfake detection! When running test.py, it will report an error -- TypeError: add_code_sample_docstrings() got an unexpected keyword argument 'tokenizer_class'.

**Comment by rshaojimmy** [comment]
Seems that you have not downloaded the bert-base-uncased checkpoint of bert model which should be downloaded automatically. Could you check it out.
