### ISSUE TITLE
download datasets

### ISSUE THREAD

**Issue by SinyWu0615** [rshaojimmy/MultiModal-DeepFake#32]
The download link of datasets has been removed. Could you share a new one? Thank you!

**Comment by rshaojimmy** [comment]
Hi, we have updated our dataset link via hugginface. Thanks.

**Comment by SinyWu0615** [comment]
Thanks!

761299486
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rshaojimmy/MultiModal-DeepFake"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rshaojimmy/MultiModal-DeepFake] download datasets (Issue #32)





 
Hi, we have updated our dataset link via hugginface. Thanks.

**Comment by SinyWu0615** [comment]
我已收到您的邮件，会尽快处理，祝您生活愉快！
