### ISSUE TITLE
Visualization Results

### ISSUE THREAD

**Issue by YYP3334522** [rshaojimmy/MultiModal-DeepFake#5]
I have read your paper and code and was deeply impressed. But I had some difficulty trying to reproduce your code, how do you visualize it? I used the grad-cam module and felt that it was difficult to integrate into this project.

**Comment by rshaojimmy** [comment]
Hi, thanks for your interest in our work! 

We use the visualization code from ALBEF: https://github.com/salesforce/ALBEF/blob/main/visualization.ipynb

Thanks.

**Comment by YYP3334522** [comment]
Thank you very much for your reply! Can I understand that visualization can be done only at the shallow manipulation stage?

**Comment by rshaojimmy** [comment]
Nope, visualizations are done at the deep manipulation stage according to each multi-modal token or the whole multi-modal sentence. We completely follow the code of visualizations of ALBEF.

**Comment by YYP3334522** [comment]
Thanks again for your reply! I hope you work smoothly and make more excellent results.

**Comment by CJL0114** [comment]
Hello, may I ask if you can provide the specific code for visualization?
